#!/bin/sh

# Update command for MacOS
# script to be put in /usr/local/bin/update

# Package managers installation
type brew >/dev/null 2>&1 || { /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"; }
type cask >/dev/null 2>&1 || { brew install cask; }
type mas >/dev/null 2>&1 || { brew install mas; }

# Update
brew update
brew upgrade
brew cask outdated|xargs brew cask reinstall
softwareupdate -ia
mas upgrade
